### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by pwz2k** [wizlee/wizlee#1]
Are you still coding by chance? Was trying to get in contact with you. If so please check my profile for my address to reach me. Thanks!

**Comment by wizlee** [comment]
hey @pwz2k , sorry for missing your comment here for so long! 
Yeah I am actively coding everyday since the time you contacted me. Visited your profile and didn't find any contact method though. 

You can hit me up using any of your preferred platform here - https://github.com/wizlee#connect-with-me.

**Comment by pwz2k** [comment]
Just shot you a message on twit
